---
title: "kmeansClusteringCourse"
output: html_document
---

```{r}
# Load packages
library(dplyr)
```

```{r}
# Load data
pokemon <- read.csv("pokemon.csv") %>%
           select(HitPoints, Attack, Defense, SpecialAttack, SpecialDefense, Speed)
```

```{r}
# Produce scree plot
## Initialize total within sum of squares error: wss
wss <- 0

## Set seed
set.seed(1)

## Look over 1 to 15 possible clusters
for (i in 1:15) {
  # Fit the model: km.out
  km.out <- kmeans(pokemon, centers = i, nstart = 20, iter.max = 50)
  # Save the within cluster sum of squares
  wss[i] <- km.out$tot.withinss
}

## Produce a scree plot
plot(1:15, wss, type = "b", 
     xlab = "Number of Clusters", 
     ylab = "Within groups sum of squares")
```

```{r}
# Select number of clusters
k <- 3

# Build model with k clusters: km.out
km.out <- kmeans(pokemon, centers = k, nstart = 20, iter.max = 50)

# View the resulting model
km.out

# Plot of Defense vs. Speed by cluster membership
plot(pokemon[, c("Defense", "Speed")],
     col = km.out$cluster,
     main = paste("k-means clustering of Pokemon with", k, "clusters"),
     xlab = "Defense", ylab = "Speed")
```

